### ISSUE TITLE
Error when using with Laravel 5.4?

### ISSUE THREAD

**Issue by dambridge** [SUKOHI/LaravelReadability#2]
`FatalThrowableError in LaravelReadabilityServiceProvider.php line 30:`
`Call to undefined method Illuminate\Foundation\Application::share()`

**Comment by SUKOHI** [comment]
Hi, dambridge.
Thank you for your message.

I've just updated the packge for L54 but I think this package it possibly does not work well because it's based on `Readability` which is not in maintenance.
The following is the original class.

http://code.google.com/p/arc90labs-readability/

**Comment by dambridge** [comment]
Thanks, will take a look!
